### ISSUE TITLE
Can't load fixtures with new system

### ISSUE THREAD

**Issue by garak** [doctrine/DoctrineFixturesBundle#215]
I'm tried to upgrade to version 3 of this bundle, e.g. turning my fixtures to services.
So, my starting point is some working fixtures with dependencies.
I changed all my fixtures classes to extend `Doctrine\Bundle\FixturesBundle\Fixture` instead of `Doctrine\Common\DataFixtures\AbstractFixture`.
When I try to load them, I get this error
>[LogicException]                                                                                                                                                                       
>The "App\DataFixtures\ORM\CategoryData" fixture class is trying to be loaded, but is not available. Make sure this class is defined as a service and tagged with "doctrine.fixture.orm"

I checked up with `console de:au DataFixtures` and I can see that my fixtures are listed as services. I also tried `console de:cont --show-private --tag doctrine.fixture.orm` and my fixtures are there.

The following are two example fixtures.
```php
<?php

namespace App\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Foo\Entity\Article;

final class ArticleData extends Fixture implements DependentFixtureInterface
{
    public function load(ObjectManager $manager): void
    {
        $art = new Article('Lorem ipsum dolor', $this->getReference('category1'));
        $manager->persist($art);
        $manager->flush();
    }

    public function getDependencies(): array
    {
        return [
            CategoryData::class,
        ];
    }
}
```

```php
<?php

namespace App\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use Foo\Entity\Category;

final class CategoryData extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $cat = new Categoy('A category');
        $manager->persist($cat);
        $this->addReference('category1', $cat);
        $manager->flush();
    }
}

```

**Comment by ruudk** [comment]
I have exactly the same issue :(

**Comment by ruudk** [comment]
It seems like a racy condition with the `DependentFixtureInterface`. 

I think this is the issue:
* Every fixture is tagged with `doctrine.fixture.orm` (also the fixtures that are dependencies of others
* When the container gets created, it will do the following for the `SymfonyFixturesLoader` service:
  - Find all tagged fixture
  - For every fixture add a method call `addFixture()`
* When the application is booted, and you use the `SymfonyFixturesLoader` for the first time, it will execute all the `addFixture` calls
* Doctrine\Common\DataFixtures\Loader::addFixture will check if the fixture implements `DependentFixtureInterface`
 - When thats the case, it will call `\Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader::createFixture`
 - That will then do a call to `\Doctrine\Common\DataFixtures\Loader::getFixture` which then checks its internal `$this->fixtures` array to see if it exist, but it doesn't exist, because it's going to be added *later*

So I think it should be changed to do this:
* First load all fixtures into the `$this->fixtures` array
* Then foreach that array, and resolve all dependencies.

**Comment by ruudk** [comment]
I will work on a fix PR to show how it could be solved! :v:

**Comment by ruudk** [comment]
@garak I created a PR to solve the issue. Can you try this PR and see if it solves your problems? I added a test instruction in the PR

**Comment by alcaeus** [comment]
3.0.1 has been released with a fix for this issue.

**Comment by sbruev** [comment]
I still have the same issue with both 3.0.1 and 3.0.2 versions of the bundle

**Comment by alcaeus** [comment]
@sbruev you have the exact same issue as OP did? That's strange - could you please post the relevant fixture classes in this ticket? Thanks!

**Comment by sbruev** [comment]
@alcaeus sorry! I had little sleep for two days, and made a childish mistake. One of my dependencies in the return array referenced to the entity class, instead of its fixture class. I've spent two days trying to catch that.
