### ISSUE TITLE
Trigger @HasLifecycleCallbacks Remove event on delete

### ISSUE THREAD

**Issue by homersimpsons** [doctrine/DoctrineFixturesBundle#237]
Hello,

This bundle is incredible, but it's missing something, the ability to trigger `@HasLifecycleCallbacks` events `PreRemove` and `PostRemove`.
Would you mind addin an option to allow this ?
In fact I use some files in fixtures and running fixtures quite often leads to a lot of elements in my files.

**Comment by alcaeus** [comment]
Sorry for the long time without a reply. The `FixtureInterface` defines a `load` method, in which you can create and persist your fixtures. Assuming that you create an entity, `persist` it in the given `ObjectManager` instance and flush that, all lifecycle callbacks and events should be fired as usual. I can only speculate as to why this isn't the case for you, but this should not need extra code in the bundle or the data-fixtures library.

**Comment by homersimpsons** [comment]
I didn't try to delete them in Fixtures, but when I run:
`php bin/console doctrine:fixtures:load`
It clear the database which is expected (no `--append` option) but it doesn't trigger Pre/Post Remove hooks

**Comment by alcaeus** [comment]
Sorry, I didn't read your initial issue was specific to the `preRemove` and `postRemove` events when using the Purger. The default `ORMPurger` class doesn't trigger these because it sends a `DELETE FROM` or `TRUNCATE TABLE` query to the database instead of fetching and removing every entity through the entity manager. While possible, this would significantly increase memory and time consumption in the purger.

What's your use case to trigger the events in the purger if I may ask?

**Comment by homersimpsons** [comment]
As I said
> In fact I use some files in fixtures and running fixtures quite often leads to a lot of elements in my files.n fact I use some files in fixtures and running fixtures quite often leads to a lot of elements in my files.

Maybe it's possible to add an option (either in the command line or fixture file)

**Comment by alcaeus** [comment]
> I use some files in fixtures

The obvious choice would be to purge all files when you purge your database. Since your database is being cleared completely, so should the files. Using lifecycle events to keep that usecase in check is a bad idea - you're better off creating a purger that purges the database (using the built-in `ORMPurger`) as well as your files.

**Comment by homersimpsons** [comment]
Hum yes, do you have any hint/doc on how to do this ?

**Comment by alcaeus** [comment]
Looking at the code, it is not as decoupled as I'd have hoped: unfortunately, the purger is created in the `LoadDataFixturesDoctrineCommand` without an option to override it: https://github.com/doctrine/DoctrineFixturesBundle/blob/b9c1c7f2afb4dfc3bcae2172dff93f1bfa5e94d3/Command/LoadDataFixturesDoctrineCommand.php#L93..L95

Unfortunately, this means overriding the original command and injecting your own purger. Also unfortunately, the `ORMExecutor` class doesn't accept any `PurgerInterface`, but only an `ORMPurger` instance, which again makes things more complicated than I had hoped. For now, you'll most likely have to override the `LoadDataFixturesDoctrineCommand` to introduce any custom behavior.

These things I mentioned should probably be changed in upcoming versions of the data-fixtures library and this bundle to allow for more flexibility, but I don't know if I'll have time to do so in the near future.

**Comment by homersimpsons** [comment]
Hum okay, as of now we need to wait an improvement in https://github.com/doctrine/data-fixtures

I think the best way could be to add an array of Purger/Loader in config so every use case could be fullfiled.

Will continue the old way (manual delete :smile: )

**Comment by DennisdeBest** [comment]
Hey I just had something similar, when running the fixtures this would upload images and convert them to webp aswell. I started with a postRemove listener but as @alcaeus just mentioned this is not taken into account when the fixtures are purged.

So to get around this I added another fixture that the others will have as a dependency. This fixture will not load anything but remove all the files in the public/uploads directory that contain `fixture` in their names.

```
public function load(ObjectManager $manager)
    {
        $prefix = __DIR__  . '/../../public/uploads/images/';
        $paths = scandir($prefix);
        foreach ($paths as $index => $path) {
            $fullPath = $prefix . $path;
            if (preg_match('/^.*fixture.*\.(webp|jpg|jpeg|png|gif|bmp)$/', $path)) {
                unlink($fullPath);
            }
        }
    }
```

In order to make this work I make the fixtures add the word fixture in the filenames of the uploaded files. 
This will not help you precisely as it is quite specific but the general idea of a fixture that deletes the files and that the other fixtures are dependent on to make sure it runs first seems to work for me.
