### ISSUE TITLE
Purging database is not reseting auto increment columns

### ISSUE THREAD

**Issue by radub** [doctrine/DoctrineFixturesBundle#277]
Running `bin/console doctrine:fixtures:load` kindly displays a warning informing the user that the database will be purged. However if there are auto-increment columns such as entity_id, those should be reset also. Loading fixtures another time may fail if the fixture data that is inserted contains database constraints.

**Comment by SenseException** [comment]
Your fixtures shouldn't have a dependency to e.g. id 42 of a relation because the auto-increment id shouldn't be hardcoded in the fixtures. Your application fixtures should work even when the next id doesn't start with 1.

**Comment by radub** [comment]
You are correct, IDs should not be hardcoded, but you may find yourself in a situation where you just want to reference certain id's just to create your fixture and move on to a bigger task. 

Also, and this is only a personal preference, I like to keep my auto-increment IDs clean (consecutive and starting from 1) - this can be affected if some of the fixtures run successfully and some fail.

Also, when I first read **database purge** I expected that everything will be reset, including auto-increment IDs.

**Comment by alcaeus** [comment]
You can use the `--purge-with-truncate` option to switch from `DELETE` to a `TRUNCATE` purger mode. It will depend on your DBMS to clear auto-increment settings on that action, and there are valid reasons to not do so.

> IDs should not be hardcoded, but you may find yourself in a situation where you just want to reference certain id's just to create your fixture and move on to a bigger task.

In that case, don't use auto-increment IDs. If you hardcode them in one place you definitely should hardcode them in another place. I would however suggest that you take a look at how to share objects between fixtures, which is explained in the documentation: https://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html#sharing-objects-between-fixtures. Then you no longer need to reference hardcoded identifiers.

Everything else is, as you said, personal preference and I don't think this is a valid reason to change the default behaviour, especially with the command-line option in place.

**Comment by mcorteel-harel** [comment]
I want to use fixtures to create a demo of my app, and when the user wants to use the app for real, load another set of fixtures to populate the needed configuration.
The problem is that I want the user to create data beginning with an ID of `1` to avoid confusion.
Using the `--purge-with-truncate` isn't an option as it fails with the following error using MariaDB:
```
Cannot truncate a table referenced in a foreign key constraint
```
I will have to reset the auto increments manually for now, but i think that this feature (as an extra option) would make a lot of sense.

**Comment by svnldwg** [comment]
I am testing a REST API. I want to check, that after creating a resource via the POST route, the correct URI to the newly created resource is included in the responses Location header. So my assertion looks like this:

`self::assertSame('http://localhost/api/todos/1', $response->headers->get('Location'));`

Because the purger truncates without resetting the auto increment, the ID increases every time I execute the test. Therefore I would have to adjust the assertion and just assert that ANY id is included in the URI.

Being able to reset the auto increment would definitely increase flexibility. Would there be any downside?

**Comment by VitorTS** [comment]
This issue should be reopen.

**Comment by acirulis** [comment]
How about writing API tests? Like:
```
$client->request('GET', '/api/customers/1');
self::assertJsonContains(['@id' => '/api/customers/1']);
```
I am thinking about creating custom Purger, which is described in the docs but it seems a bit much for such a simple behaviour.

**Comment by atanasov** [comment]
I use this bundle with ApiPlatform but in Symfony should be similar.
Using the setUp method I can set dbPopulated = true - so that the DB is not getting reset.

I use the console command to initially load Fixtures data. I don't need the Fake data to be reloaded on every test.

```
namespace App\Tests;

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;
use Hautelook\AliceBundle\PhpUnit\RefreshDatabaseTrait;

class TasksTest extends ApiTestCase
{
    use RefreshDatabaseTrait;

    protected function setUp(): void
    {
        static::$dbPopulated = true;
    }

    public function testUpdateTask(): void
    {
        $client = static::createClient();
        $client->request('PUT', '/api/tasks/1', [
            'json' => [
                'name' => 'Test Updated',
            ]
        ]);

        $this->assertResponseIsSuccessful();

        $this->assertJsonContains([
            "@id" => "/api/tasks/1",
            "name" => "Test Updated",
        ]);
    }
```

**Comment by simplyniceweb** [comment]
This should be a must especially if you're working on something that has the fixed IDs like countries which is related to other products.

**Comment by BurningDog** [comment]
In order to have my fixtures re-created with auto-increment resetting to 1, I first undo all migrations, then migrate, then run the fixtures. Like so:

```sh
console doctrine:migrations:migrate first --no-interaction --env=test
console doctrine:migrations:migrate --no-interaction --env=test
console doctrine:fixtures:load --no-interaction --env=test
```

I have a test in a `BeforeAll` folder which runs first and checks that my fixtures have been run and that the first item in a specific entity table has ID = 1. If it isn't 1, the test fails with the suggestion to run the above console commands.

It would be also a nice touch to put the 3 commands into a new Console Command class.

**Comment by kshtompel** [comment]
it can be achieved with decorating ORMPurgerFactory and ORMPurger (in test env only for instance) with adding execute additional SQL (Postgres)
$result[] = "TRUNCATE TABLE {$table} RESTART IDENTITY CASCADE"; // Or any other you require
or override on  AbstractPlatform::public function getTruncateTableSQL()
